version: '3.8'

services:
  # 1. SERVIÇO DO BANCO DE DADOS
  postgres-db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. SERVIÇO DO BACKEND (API Java)
  backend-api:
    build:
      context: ./backend # CAMINHO AJUSTADO
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Conecta ao serviço do Docker, não a localhost
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/${POSTGRES_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      API_SECURITY_TOKEN_SECRET: ${JWT_SECRET}
    depends_on:
      postgres-db:
        condition: service_healthy

  # 3. SERVIÇO DO FRONTEND (React com Hot Reload)
  frontend-app:
    build:
      context: ./front # CAMINHO AJUSTADO
      dockerfile: Dockerfile # Usando o Dockerfile de desenvolvimento
    ports:
      - "5173:5173"
    environment:
      # Variável para o Frontend saber a URL do Backend dentro do Docker
      VITE_API_BASE_URL: http://backend-api:8080/api/v1 # Usa o nome do serviço 'backend-api'
    volumes:
      # Mapeia o código do seu computador para o container (para Hot Reload)
      - ./front:/app
      # Evita que o volume de código sobrescreva o node_modules dentro do container
      - /app/node_modules
    depends_on:
      - backend-api # O Frontend só sobe depois que o Backend estiver disponível

volumes:
  postgres_data:
